application: chetanya-meghashree
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css/new/(.*)/(.*)
  static_dir: css/new/\1

- url: /js/new/(.*)/(.*)
  static_dir: js/new/\1

- url: /templates/new
  static_dir: /templates

- url: /images/new/(.*\.(gif|png|jpg))$
  static_files: images/new/\1
  upload: images/new/.*\.(gif|png|jpg)$

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
