application: chetanya-meghashree
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /css
  static_dir: app/css

- url: /js
  static_dir: app/js

- url: /(.*\.(gif|png|jpg))$
  static_files: images/\1
    upload: app/images/.*\.(gif|png|jpg)$

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"